### ISSUE TITLE
Not supported with MOya 11.0

### ISSUE THREAD

**Issue by ahmadmssm** [levibostian/Lucid#7]
In Podfile:
   
`Lucid (~> 0.4.0) was resolved to 0.4.0, which depends on
      Lucid/Core (= 0.4.0) was resolved to 0.4.0, which depends on
        Moya (~> 10.0.0)

    Moya (~> 11.0)`

**Comment by levibostian** [comment]
You are correct, @ahmedmssm. Lucid does not yet support Moya 11.0. I am still using 10 in my apps so I have not updated this library yet. 

You are very much welcome to create a pull request with this update!

**Comment by levibostian** [comment]
There is a `moya11` branch created now. I'll merge it in shortly after I test it works on one of my apps.

**Comment by levibostian** [comment]
Merged. Pushing release `0.5.0` to CocoaPods.
