### ISSUE TITLE
Error when using processErrors() with RX

### ISSUE THREAD

**Issue by ahmadmssm** [levibostian/Lucid#8]
I can not get the response from the function : 
 func statusCodeError(_ statusCode: Int, request: URLRequest?, response: URLResponse?) -> String 

I want to know if their is a way to get the response message like if i used it on the on success and the error code is 400 i still can get the error message

**Comment by levibostian** [comment]
Sorry, @ahmedmssm  could you give me a little more help with figuring out your issue? I don't quite understand what is going on. 

If you are using Rx, you should not need to use `statusCodeError()`. `processErrors()` checks for the 400 response status code for you.
